# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0018_auto_20191119_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblogarchiveplugin',
            name='render_template_choice',
        ),
        migrations.RemoveField(
            model_name='newsblogarticlesearchplugin',
            name='render_template_choice',
        ),
        migrations.RemoveField(
            model_name='newsblogauthorsplugin',
            name='render_template_choice',
        ),
        migrations.RemoveField(
            model_name='newsblogcategoriesplugin',
            name='render_template_choice',
        ),
        migrations.RemoveField(
            model_name='newsblogfeaturedarticlesplugin',
            name='render_template_choice',
        ),
        migrations.RemoveField(
            model_name='newsbloglatestarticlesplugin',
            name='render_template_choice',
        ),
        migrations.RemoveField(
            model_name='newsblogtagsplugin',
            name='render_template_choice',
        ),
    ]
